[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = '0.8.15'

remappings = [
  "forge-std=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config